before:
  hooks:
    - go install fyne.io/fyne/v2/cmd/fyne@latest
    - go mod tidy
    - go generate ./...
# Verifiable build
# https://goreleaser.com/customization/gomod/#go-modules
gomod:
  proxy: true
builds:
  - targets:
      - linux_amd64
    # Reproducible build
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
# Enable macOS "Universal Binaries" (amd64 + arm binaries)
universal_binaries:
  - replace: true
archives:
  # Upload the binaries, not archives
  - format: binary
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
release:
  draft: true
  footer: |
    **Full Changelog**: https://github.com/tomsquest/fynodoro/compare/{{ .PreviousTag }}...{{ .Tag }}
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^doc:'
      - '^ci:'
      - '^test:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
